name: New CFE workflow notifications
on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: write

jobs:
  send-slack-notification:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-20.04
    steps:
      - name: Debug GitHub Context
        run: |
          echo "${{ toJson(github) }}"

      - name: Check Slack Token and Channel
        run: |
          echo "SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}"
          echo "Slack Channel: general"
        
      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: "test"
          slack-text: |
            Test
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true
      
      - name: Close the issue
        run: gh issue close --comment "Closing issue. https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
