name: New CFE/PRR workflow notifications
on:
  issues:
    types: [labeled]

permissions: {}

jobs:
  prep:
    if: github.event.label.name == 'Approved' || github.event.label.name == 'Rejected'
    runs-on: ubuntu-20.04
    outputs:
      release_number: ${{ steps.extract-release.outputs.RELEASE_NUMBER }}
    steps:
      - name: Extract Release Number from Issue Body
        id: extract-release
        uses: actions/github-script@v7
        with:
          script: |
            const event = ${{ toJSON( github.event ) }}
            const body = event.issue.body;

            // Regular expression to match the release number after the specific question
            const releaseRegex = /Which release does this request apply to\?.*?\n([0-9]+\.[0-9]+)/s;

            // Match the body against the regex
            const match = body.match(releaseRegex);

            // Check if a valid release number was found
            if (match && match[1]) {
              const releaseNumber = match[1];

              // Log the release number and set it as a GitHub output
              console.log(`Valid release number: ${releaseNumber}`);
              core.setOutput('RELEASE_NUMBER', releaseNumber);
            } else {
              // If no valid release number is found, fail the step
              core.setFailed("No valid release number found after the 'Which release does this request apply to?' section. Aborting.");
            }

  cfe-created:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-20.04
    steps:
      - name: Set Slack Message
        id: set-message
        run: |
          if [ "${{ github.event.label.name }}" == 'code freeze exception' ]; then
            MESSAGE=":arrow_right: New CFE request: ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}"
          else
            MESSAGE=":arrow_right: New PRR request: ${{ github.event.issue.title }} ${{ github.event.issue.html_url }}"
          fi

          echo "SLACK_MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
          slack-text: ${{ env.SLACK_MESSAGE }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true

  request-approved:
    if: ${{ github.event.label.name == 'Approved' }}
    runs-on: ubuntu-20.04
    needs:
      - prep
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Extract PR number from issue body
        id: extract-pr
        uses: actions/github-script@v7
        with:
          script: |
            const event = ${{ toJSON( github.event ) }}
            const body = event.issue.body;

            // Regular expression to match the PR link that follows the specific question
            const prRegex = /Which PR needs to be included\?.*?\n(https:\/\/github\.com\/[a-zA-Z0-9_\-]+\/[a-zA-Z0-9_\-]+\/pull\/([0-9]+))/s;

            // Match the body against the regex
            const match = body.match(prRegex);

            // Check if a valid PR number was found
            if (match && match[2]) {
              const prNumber = match[2];

              // Log the PR number and set it as a GitHub output
              console.log(`Valid PR number: ${prNumber}`);
              core.setOutput('PR_NUMBER', prNumber);
            } else {
              // If no valid PR number is found, fail the step
              core.setFailed("No valid PR found after the 'Which PR' section. Aborting.");
            }

      - name: Add label 'cherry pick to trunk' to PR
        run: |
          OWNER="${{ github.event.repository.owner.login }}"
          REPO="${{ github.event.repository.name }}"
          gh pr edit ${{ steps.extract-pr.outputs.PR_NUMBER }} --add-label "cherry pick to trunk" --repo $OWNER/$REPO
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ env.PR_URL }}

      - name: Add label 'cherry pick to frozen release' to PR
        if: contains(github.event.issue.labels.*.name, 'point release request')
        run: |
          OWNER="${{ github.event.repository.owner.login }}"
          REPO="${{ github.event.repository.name }}"
          gh pr edit $PR_NUMBER --add-label "cherry pick to frozen release" --repo $OWNER/$REPO
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Milestone to the Issue
        run: |
          MILESTONE="$RELEASE_NUMBER.0"
          echo "Applying milestone: $MILESTONE"
          gh issue edit ${{ github.event.issue.html_url }} --milestone "$MILESTONE"
        env:
          RELEASE_NUMBER: ${{ needs.prep.outputs.release_number }}
          GH_TOKEN: ${{ github.token }}

      - name: Set Slack Message
        id: set-slack-message
        run: |
          if [[ "${{ github.event.issue.labels.*.name }}" == *'code freeze exception'* ]]; then
            MESSAGE=":white_check_mark: CFE request approved: ${{ github.event.issue.title }}\n${{ github.event.issue.html_url }}"
          else
            MESSAGE=":white_check_mark: PRR request approved: ${{ github.event.issue.title }}\n${{ github.event.issue.html_url }}"
          fi

          echo "SLACK_MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_CORE_RELESES_DAILY_SLACK_CHANNEL }}
          slack-text: ${{ env.SLACK_MESSAGE }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true

  request-rejected:
    if: ${{ github.event.label.name == 'Rejected' }}
    runs-on: ubuntu-20.04
    needs:
      - prep
    permissions:
      issues: write
    steps:
      - name: Apply Milestone to the Issue
        run: |
          MILESTONE="$RELEASE_NUMBER.0"
          echo "Applying milestone: $MILESTONE"
          gh issue edit ${{ github.event.issue.html_url }} --milestone "$MILESTONE"
        env:
          RELEASE_NUMBER: ${{ needs.prep.outputs.release_number }}
          GH_TOKEN: ${{ github.token }}

      - name: Close CFE Issue
        run: gh issue close --comment "Closing issue as the request is rejected - ${{ github.event.issue.html_url }}" "${{ github.event.issue.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Slack Message
        id: set-slack-message
        run: |
          if [[ "${{ github.event.issue.labels.*.name }}" == *'code freeze exception'* ]]; then
            MESSAGE=":x: CFE request rejected: ${{ github.event.issue.title }}\n${{ github.event.issue.html_url }}"
          else
            MESSAGE=":x: PRR request rejected: ${{ github.event.issue.title }}\n${{ github.event.issue.html_url }}"
          fi

          echo "SLACK_MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_CORE_RELESES_DAILY_SLACK_CHANNEL }}
          slack-text: ${{ env.SLACK_MESSAGE }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true
