name: New CFE workflow notifications
on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      - name: Send Slack message
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify-slack
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: general
          slack-text: |
            CFE created!
            ${{ toJson(github) }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
      - name: Close the issue
        run: gh issue close --comment "Closing issue. **Only WooCommerce employees can open CFEs.** _We probably need a more polite message here._" "https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}